# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DelegationApp-iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DelegationApp-iOS
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  
end

target 'DelegationApp-macOS' do
  use_frameworks!

  # Pods for 'DelegationApp-macOS'
  # pod 'Firebase', :path => '/Users/erikphillips/Desktop/senior_project/delegation_app/firebase-ios-sdk'
  pod 'FirebaseCore', :path => '/Users/erikphillips/Desktop/senior_project/delegation_app/firebase-ios-sdk'
  pod 'FirebaseAuth', :path => '/Users/erikphillips/Desktop/senior_project/delegation_app/firebase-ios-sdk'
  pod 'FirebaseDatabase', :path => '/Users/erikphillips/Desktop/senior_project/delegation_app/firebase-ios-sdk'

end
