# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'delegation-app-ios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for delegation-app-ios
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  
  target 'delegation-app-iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'delegation-app-iosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
